fix AttributeError: module 'datetime' has no attribute 'UTC'
datetime.UTC was introduced in Python 3.11 so older versions throw
an AttributeError. Add handling to use the older version if UTC is
not found.

Signed-off-by: Christian Hewitt <christianshewitt@gmail.com>